name: Build, Test, & Deploy on Workflow Dispatch

on:
  push:
    branches:
      - cicd-test
  pull_request:
    branches:
      - cicd-test
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Clean and Build Release APK
        run: ./gradlew clean assembleRelease --stacktrace
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Upload Crashlytics Mapping File
        run: ./gradlew :app:uploadCrashlyticsMappingFileRelease
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Check build output
        run: ls -R app/build/outputs

      - name: Verify APK file
        run: |
          if [ -f app/build/outputs/apk/release/app-release.apk ]; then
            echo "APK file exists"
          else
            echo "APK file does not exist"
            exit 1
          fi

      - name: Upload and Distribute App
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: 'tester'
          file: app/release/app-release.apk
          releaseNotes: |
            Changes in this build:
            - ${{ github.event.head_commit.message }}

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: app/build/test-results

      - name: Upload build outputs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-outputs
          path: app/build/outputs